# Generated by Django 4.1 on 2022-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='logo/company/plug.png', upload_to='logo/company/'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='logo/specialty/plug.png', upload_to='logo/specialty/'),
        ),
    ]
